<a href="https://colab.research.google.com/github/SahilKamble-dev/it-DS-With-Python---Lab--experiments/blob/main/MINI%20PROJECT%20NOTEBOOK%2001.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Project: Weather Prediction Dataset**

**Dataset Selection**

The dataset used in this project is a Weather Prediction dataset. It contains weather-related attributes such as temperature, humidity, pressure, cloud cover, and precipitation for different cities. The dataset is used to analyze weather patterns and prepare it for machine learning models.

 1. Import Libraries

In [ ]:
import pandas as pd
import numpy as np

2. Upload Dataset

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving weather_prediction_dataset_light.csv to weather_prediction_dataset_light.csv

3 :- Then Load Dataset

In [ ]:
import pandas as pd

df = pd.read_csv("weather_prediction_dataset_light.csv")
df.head()

,DATE,MONTH,BASEL_cloud_cover,BASEL_humidity,BASEL_pressure,BASEL_global_radiation,BASEL_precipitation,BASEL_sunshine,BASEL_temp_mean,BASEL_temp_min,...,SONNBLICK_temp_mean,SONNBLICK_temp_min,SONNBLICK_temp_max,TOURS_humidity,TOURS_pressure,TOURS_global_radiation,TOURS_precipitation,TOURS_temp_mean,TOURS_temp_min,TOURS_temp_max
0,20000101,1,8,0.89,1.0286,0.20,0.03,0.0,2.9,1.6,...,-15.2,-17.0,-13.4,0.97,1.0275,0.25,0.04,8.5,7.2,9.8
1,20000102,1,8,0.87,1.0318,0.25,0.00,0.0,3.6,2.7,...,-13.7,-15.0,-12.3,0.99,1.0293,0.17,0.16,7.9,6.6,9.2
2,20000103,1,5,0.81,1.0314,0.50,0.00,3.7,2.2,0.1,...,-9.2,-12.5,-5.8,0.91,1.0267,0.27,0.00,8.1,6.6,9.6
3,20000104,1,7,0.79,1.0262,0.63,0.35,6.9,3.9,0.5,...,-5.6,-7.0,-4.2,0.95,1.0222,0.11,0.44,8.6,6.4,10.8
4,20000105,1,5,0.90,1.0246,0.51,0.07,3.7,6.0,3.8,...,-7.6,-9.4,-5.8,0.95,1.0209,0.39,0.04,8.0,6.4,9.5

4 :- Understanding the Data

In [ ]:
df.shape

(3654, 91)

In [ ]:
df.columns

Index(['DATE', 'MONTH', 'BASEL_cloud_cover', 'BASEL_humidity',
       'BASEL_pressure', 'BASEL_global_radiation', 'BASEL_precipitation',
       'BASEL_sunshine', 'BASEL_temp_mean', 'BASEL_temp_min', 'BASEL_temp_max',
       'DE_BILT_cloud_cover', 'DE_BILT_humidity', 'DE_BILT_pressure',
       'DE_BILT_global_radiation', 'DE_BILT_precipitation', 'DE_BILT_sunshine',
       'DE_BILT_temp_mean', 'DE_BILT_temp_min', 'DE_BILT_temp_max',
       'DRESDEN_cloud_cover', 'DRESDEN_humidity', 'DRESDEN_global_radiation',
       'DRESDEN_precipitation', 'DRESDEN_sunshine', 'DRESDEN_temp_mean',
       'DRESDEN_temp_min', 'DRESDEN_temp_max', 'DUSSELDORF_cloud_cover',
       'DUSSELDORF_humidity', 'DUSSELDORF_pressure',
       'DUSSELDORF_global_radiation', 'DUSSELDORF_precipitation',
       'DUSSELDORF_sunshine', 'DUSSELDORF_temp_mean', 'DUSSELDORF_temp_min',
       'DUSSELDORF_temp_max', 'HEATHROW_cloud_cover', 'HEATHROW_humidity',
       'HEATHROW_pressure', 'HEATHROW_global_radiation',
       'HEATHROW_precipitation', 'HEATHROW_sunshine', 'HEATHROW_temp_mean',
       'HEATHROW_temp_min', 'HEATHROW_temp_max', 'KASSEL_humidity',
       'KASSEL_pressure', 'KASSEL_global_radiation', 'KASSEL_precipitation',
       'KASSEL_sunshine', 'KASSEL_temp_mean', 'KASSEL_temp_min',
       'KASSEL_temp_max', 'MAASTRICHT_cloud_cover', 'MAASTRICHT_humidity',
       'MAASTRICHT_pressure', 'MAASTRICHT_global_radiation',
       'MAASTRICHT_precipitation', 'MAASTRICHT_sunshine',
       'MAASTRICHT_temp_mean', 'MAASTRICHT_temp_min', 'MAASTRICHT_temp_max',
       'MALMO_precipitation', 'MALMO_temp_mean', 'MALMO_temp_min',
       'MALMO_temp_max', 'MUENCHEN_cloud_cover', 'MUENCHEN_humidity',
       'MUENCHEN_pressure', 'MUENCHEN_global_radiation',
       'MUENCHEN_precipitation', 'MUENCHEN_sunshine', 'MUENCHEN_temp_mean',
       'MUENCHEN_temp_min', 'MUENCHEN_temp_max', 'SONNBLICK_cloud_cover',
       'SONNBLICK_humidity', 'SONNBLICK_global_radiation',
       'SONNBLICK_precipitation', 'SONNBLICK_sunshine', 'SONNBLICK_temp_mean',
       'SONNBLICK_temp_min', 'SONNBLICK_temp_max', 'TOURS_humidity',
       'TOURS_pressure', 'TOURS_global_radiation', 'TOURS_precipitation',
       'TOURS_temp_mean', 'TOURS_temp_min', 'TOURS_temp_max'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3654 entries, 0 to 3653
Data columns (total 91 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   DATE                         3654 non-null   int64
 1   MONTH                        3654 non-null   int64
 2   BASEL_cloud_cover            3654 non-null   int64
 3   BASEL_humidity               3654 non-null   float64
 4   BASEL_pressure               3654 non-null   float64
 5   BASEL_global_radiation       3654 non-null   float64
 6   BASEL_precipitation          3654 non-null   float64
 7   BASEL_sunshine               3654 non-null   float64
 8   BASEL_temp_mean              3654 non-null   float64
 9   BASEL_temp_min               3654 non-null   float64
 10  BASEL_temp_max               3654 non-null   float64
 11  DE_BILT_cloud_cover          3654 non-null   int64
 12  DE_BILT_humidity             3654 non-null   float64
 13  DE_BILT_pressure             3654 non-null   float64
 14  DE_BILT_global_radiation     3654 non-null   float64
 15  DE_BILT_precipitation        3654 non-null   float64
 16  DE_BILT_sunshine             3654 non-null   float64
 17  DE_BILT_temp_mean            3654 non-null   float64
 18  DE_BILT_temp_min             3654 non-null   float64
 19  DE_BILT_temp_max             3654 non-null   float64
 20  DRESDEN_cloud_cover          3654 non-null   int64
 21  DRESDEN_humidity             3654 non-null   float64
 22  DRESDEN_global_radiation     3654 non-null   float64
 23  DRESDEN_precipitation        3654 non-null   float64
 24  DRESDEN_sunshine             3654 non-null   float64
 25  DRESDEN_temp_mean            3654 non-null   float64
 26  DRESDEN_temp_min             3654 non-null   float64
 27  DRESDEN_temp_max             3654 non-null   float64
 28  DUSSELDORF_cloud_cover       3654 non-null   int64
 29  DUSSELDORF_humidity          3654 non-null   float64
 30  DUSSELDORF_pressure          3654 non-null   float64
 31  DUSSELDORF_global_radiation  3654 non-null   float64
 32  DUSSELDORF_precipitation     3654 non-null   float64
 33  DUSSELDORF_sunshine          3654 non-null   float64
 34  DUSSELDORF_temp_mean         3654 non-null   float64
 35  DUSSELDORF_temp_min          3654 non-null   float64
 36  DUSSELDORF_temp_max          3654 non-null   float64
 37  HEATHROW_cloud_cover         3654 non-null   int64
 38  HEATHROW_humidity            3654 non-null   float64
 39  HEATHROW_pressure            3654 non-null   float64
 40  HEATHROW_global_radiation    3654 non-null   float64
 41  HEATHROW_precipitation       3654 non-null   float64
 42  HEATHROW_sunshine            3654 non-null   float64
 43  HEATHROW_temp_mean           3654 non-null   float64
 44  HEATHROW_temp_min            3654 non-null   float64
 45  HEATHROW_temp_max            3654 non-null   float64
 46  KASSEL_humidity              3654 non-null   float64
 47  KASSEL_pressure              3654 non-null   float64
 48  KASSEL_global_radiation      3654 non-null   float64
 49  KASSEL_precipitation         3654 non-null   float64
 50  KASSEL_sunshine              3654 non-null   float64
 51  KASSEL_temp_mean             3654 non-null   float64
 52  KASSEL_temp_min              3654 non-null   float64
 53  KASSEL_temp_max              3654 non-null   float64
 54  MAASTRICHT_cloud_cover       3654 non-null   int64
 55  MAASTRICHT_humidity          3654 non-null   float64
 56  MAASTRICHT_pressure          3654 non-null   float64
 57  MAASTRICHT_global_radiation  3654 non-null   float64
 58  MAASTRICHT_precipitation     3654 non-null   float64
 59  MAASTRICHT_sunshine          3654 non-null   float64
 60  MAASTRICHT_temp_mean         3654 non-null   float64
 61  MAASTRICHT_temp_min          3654 non-null   float64
 62  MAASTRICHT_temp_max          3654 non-null   float64
 63  MALMO_precipitation          3654 non-null   float64
 64  MALMO_temp_mean              3654 non-null   float64
 65  MALMO_temp_min               3654 non-null   float64
 66  MALMO_temp_max               3654 non-null   float64
 67  MUENCHEN_cloud_cover         3654 non-null   int64
 68  MUENCHEN_humidity            3654 non-null   float64
 69  MUENCHEN_pressure            3654 non-null   float64
 70  MUENCHEN_global_radiation    3654 non-null   float64
 71  MUENCHEN_precipitation       3654 non-null   float64
 72  MUENCHEN_sunshine            3654 non-null   float64
 73  MUENCHEN_temp_mean           3654 non-null   float64
 74  MUENCHEN_temp_min            3654 non-null   float64
 75  MUENCHEN_temp_max            3654 non-null   float64
 76  SONNBLICK_cloud_cover        3654 non-null   int64
 77  SONNBLICK_humidity           3654 non-null   float64
 78  SONNBLICK_global_radiation   3654 non-null   float64
 79  SONNBLICK_precipitation      3654 non-null   float64
 80  SONNBLICK_sunshine           3654 non-null   float64
 81  SONNBLICK_temp_mean          3654 non-null   float64
 82  SONNBLICK_temp_min           3654 non-null   float64
 83  SONNBLICK_temp_max           3654 non-null   float64
 84  TOURS_humidity               3654 non-null   float64
 85  TOURS_pressure               3654 non-null   float64
 86  TOURS_global_radiation       3654 non-null   float64
 87  TOURS_precipitation          3654 non-null   float64
 88  TOURS_temp_mean              3654 non-null   float64
 89  TOURS_temp_min               3654 non-null   float64
 90  TOURS_temp_max               3654 non-null   float64
dtypes: float64(81), int64(10)
memory usage: 2.5 MB

In [ ]:
df.describe

<bound method NDFrame.describe of           DATE  MONTH  BASEL_cloud_cover  BASEL_humidity  BASEL_pressure  \
0     20000101      1                  8            0.89          1.0286
1     20000102      1                  8            0.87          1.0318
2     20000103      1                  5            0.81          1.0314
3     20000104      1                  7            0.79          1.0262
4     20000105      1                  5            0.90          1.0246
...        ...    ...                ...             ...             ...
3649  20091228     12                  7            0.82          1.0084
3650  20091229     12                  7            0.92          1.0028
3651  20091230     12                  8            0.92          0.9979
3652  20091231     12                  7            0.93          0.9958
3653  20100101      1                  8            0.93          0.9965

      BASEL_global_radiation  BASEL_precipitation  BASEL_sunshine  \
0                       0.20                 0.03             0.0
1                       0.25                 0.00             0.0
2                       0.50                 0.00             3.7
3                       0.63                 0.35             6.9
4                       0.51                 0.07             3.7
...                      ...                  ...             ...
3649                    0.28                 0.42             0.3
3650                    0.22                 1.68             0.2
3651                    0.07                 1.54             0.0
3652                    0.17                 0.57             0.1
3653                    0.08                 0.56             0.0

      BASEL_temp_mean  BASEL_temp_min  ...  SONNBLICK_temp_mean  \
0                 2.9             1.6  ...                -15.2
1                 3.6             2.7  ...                -13.7
2                 2.2             0.1  ...                 -9.2
3                 3.9             0.5  ...                 -5.6
4                 6.0             3.8  ...                 -7.6
...               ...             ...  ...                  ...
3649              3.2             1.0  ...                -15.1
3650              4.5             2.4  ...                -10.9
3651              8.5             7.5  ...                 -6.6
3652              6.6             4.3  ...                 -7.2
3653              2.9            -0.2  ...                 -9.7

      SONNBLICK_temp_min  SONNBLICK_temp_max  TOURS_humidity  TOURS_pressure  \
0                  -17.0               -13.4            0.97          1.0275
1                  -15.0               -12.3            0.99          1.0293
2                  -12.5                -5.8            0.91          1.0267
3                   -7.0                -4.2            0.95          1.0222
4                   -9.4                -5.8            0.95          1.0209
...                  ...                 ...             ...             ...
3649               -16.2               -14.0            0.95          1.0011
3650               -14.4                -7.3            0.89          0.9966
3651                -7.6                -5.6            0.88          0.9939
3652                -8.9                -5.4            0.88          0.9933
3653               -11.5                -7.9            0.86          1.0040

      TOURS_global_radiation  TOURS_precipitation  TOURS_temp_mean  \
0                       0.25                 0.04              8.5
1                       0.17                 0.16              7.9
2                       0.27                 0.00              8.1
3                       0.11                 0.44              8.6
4                       0.39                 0.04              8.0
...                      ...                  ...              ...
3649                    0.22                 1.50              6.2
3650                    0.24                 0.40             10.4
3651                    0.24                 1.00             10.0
3652                    0.58                 0.02              8.5
3653                    0.11                 0.00              0.5

      TOURS_temp_min  TOURS_temp_max
0                7.2             9.8
1                6.6             9.2
2                6.6             9.6
3                6.4            10.8
4                6.4             9.5
...              ...             ...
3649             1.8            10.6
3650             6.2            14.5
3651             8.7            11.3
3652             6.2            10.9
3653            -0.7             1.8

[3654 rows x 91 columns]>

Explanation

Dataset contains weather-related features like temperature, humidity, wind, etc.
Target variable is the last column (prediction output).

5. Check Missing Values

In [ ]:
df.isnull().sum()

DATE                      0
MONTH                     0
BASEL_cloud_cover         0
BASEL_humidity            0
BASEL_pressure            0
                         ..
TOURS_global_radiation    0
TOURS_precipitation       0
TOURS_temp_mean           0
TOURS_temp_min            0
TOURS_temp_max            0
Length: 91, dtype: int64

After checking missing values using df.isnull().sum(), it was observed that all columns contain 0 missing values. Hence, no data cleaning was required for missing values.

6. Check Duplicate Data

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

for col in df.columns:
    if df[col].dtype == 'object':
        df[col] = le.fit_transform(df[col])

df.head()

,DATE,MONTH,BASEL_cloud_cover,BASEL_humidity,BASEL_pressure,BASEL_global_radiation,BASEL_precipitation,BASEL_sunshine,BASEL_temp_mean,BASEL_temp_min,...,SONNBLICK_temp_mean,SONNBLICK_temp_min,SONNBLICK_temp_max,TOURS_humidity,TOURS_pressure,TOURS_global_radiation,TOURS_precipitation,TOURS_temp_mean,TOURS_temp_min,TOURS_temp_max
0,20000101,1,8,0.89,1.0286,0.20,0.03,0.0,2.9,1.6,...,-15.2,-17.0,-13.4,0.97,1.0275,0.25,0.04,8.5,7.2,9.8
1,20000102,1,8,0.87,1.0318,0.25,0.00,0.0,3.6,2.7,...,-13.7,-15.0,-12.3,0.99,1.0293,0.17,0.16,7.9,6.6,9.2
2,20000103,1,5,0.81,1.0314,0.50,0.00,3.7,2.2,0.1,...,-9.2,-12.5,-5.8,0.91,1.0267,0.27,0.00,8.1,6.6,9.6
3,20000104,1,7,0.79,1.0262,0.63,0.35,6.9,3.9,0.5,...,-5.6,-7.0,-4.2,0.95,1.0222,0.11,0.44,8.6,6.4,10.8
4,20000105,1,5,0.90,1.0246,0.51,0.07,3.7,6.0,3.8,...,-7.6,-9.4,-5.8,0.95,1.0209,0.39,0.04,8.0,6.4,9.5

Warning: Total number of columns (91) exceeds max_columns (20) limiting to first (20) columns.

7. Convert Categorical Data to Numeric

 Final Conclusion

The dataset was successfully cleaned and preprocessed. It contains no missing or duplicate values, and all necessary transformations were applied. The dataset is now ready for model building and prediction.